### ISSUE TITLE
Please explain with an example

### ISSUE THREAD

**Issue by santosh-hegde** [rook2pawn/node-ddos#22]
I have some confusion with this module.
Here is my config:
```
  ddos = new Ddos({
        maxcount: 3,
        trustProxy: false, 
        includeUserAgent: false,
        burst: 3,
        limit: 3,
        maxexpiry:3600,
        checkinterval: 3600, 
        responseStatus: 200, 
        errormessage: "Too Many Requests"
    }),
```

With this, 
When the count reaches 4, the request is blocked for 1 sec. When another request came, further requests blocked for another 2sec and it continues like 4,8,16,32
When will this values become 32,16,8,4,2 and remove blocking?

**Comment by micksatana** [comment]
@santosh-hegde 

`checkinterval` should not be too high else it won't recheck the table and expiry never go down by the `checkinterval` time. 

Let's say, in your case, 
`expiry` is default to 1 second. it will goes up 2, 4, 8, ... then blockage will continue up to `maxexpiry` which is 3600 seconds . 
`checkinterval` will run check at every 3600 seconds. So every 3600 seconds your expiry will reduce by 3600 seconds.

Kindly close the issue if this helps.

**Comment by rook2pawn** [comment]
Thanks @micksatana Let me try to explain it another way

When the count reaches 4, since the `limit` is 3 then the request is blocked, correct. Since the `burst` is 3, then the fourth request and the expiry up twice the previous, so expiry 1 goes to 2. I think what will help is a copy-paste code example that demonstrates the requests with setTimeouts and logging the output. 

Yes, `checkInterval` should be 1 second
